// Generated by gencpp from file mycobot_320_communication/SetAngles.msg
// DO NOT EDIT!


#ifndef MYCOBOT_320_COMMUNICATION_MESSAGE_SETANGLES_H
#define MYCOBOT_320_COMMUNICATION_MESSAGE_SETANGLES_H

#include <ros/service_traits.h>


#include <mycobot_320_communication/SetAnglesRequest.h>
#include <mycobot_320_communication/SetAnglesResponse.h>


namespace mycobot_320_communication
{

struct SetAngles
{

typedef SetAnglesRequest Request;
typedef SetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngles
} // namespace mycobot_320_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_320_communication::SetAngles > {
  static const char* value()
  {
    return "55187c842c58f84693a24ea9acdaa608";
  }

  static const char* value(const ::mycobot_320_communication::SetAngles&) { return value(); }
};

template<>
struct DataType< ::mycobot_320_communication::SetAngles > {
  static const char* value()
  {
    return "mycobot_320_communication/SetAngles";
  }

  static const char* value(const ::mycobot_320_communication::SetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_320_communication::SetAnglesRequest> should match
// service_traits::MD5Sum< ::mycobot_320_communication::SetAngles >
template<>
struct MD5Sum< ::mycobot_320_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_320_communication::SetAngles >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_320_communication::SetAnglesRequest> should match
// service_traits::DataType< ::mycobot_320_communication::SetAngles >
template<>
struct DataType< ::mycobot_320_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_320_communication::SetAngles >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_320_communication::SetAnglesResponse> should match
// service_traits::MD5Sum< ::mycobot_320_communication::SetAngles >
template<>
struct MD5Sum< ::mycobot_320_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_320_communication::SetAngles >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_320_communication::SetAnglesResponse> should match
// service_traits::DataType< ::mycobot_320_communication::SetAngles >
template<>
struct DataType< ::mycobot_320_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_320_communication::SetAngles >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_320_COMMUNICATION_MESSAGE_SETANGLES_H
