// Generated by gencpp from file mycobot_320_communication/SetCoords.msg
// DO NOT EDIT!


#ifndef MYCOBOT_320_COMMUNICATION_MESSAGE_SETCOORDS_H
#define MYCOBOT_320_COMMUNICATION_MESSAGE_SETCOORDS_H

#include <ros/service_traits.h>


#include <mycobot_320_communication/SetCoordsRequest.h>
#include <mycobot_320_communication/SetCoordsResponse.h>


namespace mycobot_320_communication
{

struct SetCoords
{

typedef SetCoordsRequest Request;
typedef SetCoordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCoords
} // namespace mycobot_320_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_320_communication::SetCoords > {
  static const char* value()
  {
    return "95b4f407876223fa17222d70490cde51";
  }

  static const char* value(const ::mycobot_320_communication::SetCoords&) { return value(); }
};

template<>
struct DataType< ::mycobot_320_communication::SetCoords > {
  static const char* value()
  {
    return "mycobot_320_communication/SetCoords";
  }

  static const char* value(const ::mycobot_320_communication::SetCoords&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_320_communication::SetCoordsRequest> should match
// service_traits::MD5Sum< ::mycobot_320_communication::SetCoords >
template<>
struct MD5Sum< ::mycobot_320_communication::SetCoordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_320_communication::SetCoords >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_320_communication::SetCoordsRequest> should match
// service_traits::DataType< ::mycobot_320_communication::SetCoords >
template<>
struct DataType< ::mycobot_320_communication::SetCoordsRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_320_communication::SetCoords >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_320_communication::SetCoordsResponse> should match
// service_traits::MD5Sum< ::mycobot_320_communication::SetCoords >
template<>
struct MD5Sum< ::mycobot_320_communication::SetCoordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_320_communication::SetCoords >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetCoordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_320_communication::SetCoordsResponse> should match
// service_traits::DataType< ::mycobot_320_communication::SetCoords >
template<>
struct DataType< ::mycobot_320_communication::SetCoordsResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_320_communication::SetCoords >::value();
  }
  static const char* value(const ::mycobot_320_communication::SetCoordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_320_COMMUNICATION_MESSAGE_SETCOORDS_H
