(cl:in-package mybuddy_communication-srv)
(cl:export '(JOINT_0-VAL
          JOINT_0
          JOINT_1-VAL
          JOINT_1
          JOINT_2-VAL
          JOINT_2
          JOINT_3-VAL
          JOINT_3
          JOINT_4-VAL
          JOINT_4
          JOINT_5-VAL
          JOINT_5
          JOINT_6-VAL
          JOINT_6
          JOINT_7-VAL
          JOINT_7
          JOINT_8-VAL
          JOINT_8
          JOINT_9-VAL
          JOINT_9
          JOINT_10-VAL
          JOINT_10
          JOINT_11-VAL
          JOINT_11
          JOINT_12-VAL
          JOINT_12
          SPEED-VAL
          SPEED
          FLAG-VAL
          FLAG
))