// Generated by gencpp from file mycobot_communication/GetAngles.msg
// DO NOT EDIT!


#ifndef MYCOBOT_COMMUNICATION_MESSAGE_GETANGLES_H
#define MYCOBOT_COMMUNICATION_MESSAGE_GETANGLES_H

#include <ros/service_traits.h>


#include <mycobot_communication/GetAnglesRequest.h>
#include <mycobot_communication/GetAnglesResponse.h>


namespace mycobot_communication
{

struct GetAngles
{

typedef GetAnglesRequest Request;
typedef GetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAngles
} // namespace mycobot_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_communication::GetAngles > {
  static const char* value()
  {
    return "8ce9dd71b812ac669ff127f95e5ce8ab";
  }

  static const char* value(const ::mycobot_communication::GetAngles&) { return value(); }
};

template<>
struct DataType< ::mycobot_communication::GetAngles > {
  static const char* value()
  {
    return "mycobot_communication/GetAngles";
  }

  static const char* value(const ::mycobot_communication::GetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_communication::GetAnglesRequest> should match
// service_traits::MD5Sum< ::mycobot_communication::GetAngles >
template<>
struct MD5Sum< ::mycobot_communication::GetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::GetAngles >::value();
  }
  static const char* value(const ::mycobot_communication::GetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::GetAnglesRequest> should match
// service_traits::DataType< ::mycobot_communication::GetAngles >
template<>
struct DataType< ::mycobot_communication::GetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::GetAngles >::value();
  }
  static const char* value(const ::mycobot_communication::GetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_communication::GetAnglesResponse> should match
// service_traits::MD5Sum< ::mycobot_communication::GetAngles >
template<>
struct MD5Sum< ::mycobot_communication::GetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::GetAngles >::value();
  }
  static const char* value(const ::mycobot_communication::GetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::GetAnglesResponse> should match
// service_traits::DataType< ::mycobot_communication::GetAngles >
template<>
struct DataType< ::mycobot_communication::GetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::GetAngles >::value();
  }
  static const char* value(const ::mycobot_communication::GetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_COMMUNICATION_MESSAGE_GETANGLES_H
