// Generated by gencpp from file mycobot_communication/GetCoords.msg
// DO NOT EDIT!


#ifndef MYCOBOT_COMMUNICATION_MESSAGE_GETCOORDS_H
#define MYCOBOT_COMMUNICATION_MESSAGE_GETCOORDS_H

#include <ros/service_traits.h>


#include <mycobot_communication/GetCoordsRequest.h>
#include <mycobot_communication/GetCoordsResponse.h>


namespace mycobot_communication
{

struct GetCoords
{

typedef GetCoordsRequest Request;
typedef GetCoordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCoords
} // namespace mycobot_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mycobot_communication::GetCoords > {
  static const char* value()
  {
    return "740a0696f94797c91679d50dca7e75ad";
  }

  static const char* value(const ::mycobot_communication::GetCoords&) { return value(); }
};

template<>
struct DataType< ::mycobot_communication::GetCoords > {
  static const char* value()
  {
    return "mycobot_communication/GetCoords";
  }

  static const char* value(const ::mycobot_communication::GetCoords&) { return value(); }
};


// service_traits::MD5Sum< ::mycobot_communication::GetCoordsRequest> should match
// service_traits::MD5Sum< ::mycobot_communication::GetCoords >
template<>
struct MD5Sum< ::mycobot_communication::GetCoordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::GetCoords >::value();
  }
  static const char* value(const ::mycobot_communication::GetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::GetCoordsRequest> should match
// service_traits::DataType< ::mycobot_communication::GetCoords >
template<>
struct DataType< ::mycobot_communication::GetCoordsRequest>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::GetCoords >::value();
  }
  static const char* value(const ::mycobot_communication::GetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mycobot_communication::GetCoordsResponse> should match
// service_traits::MD5Sum< ::mycobot_communication::GetCoords >
template<>
struct MD5Sum< ::mycobot_communication::GetCoordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mycobot_communication::GetCoords >::value();
  }
  static const char* value(const ::mycobot_communication::GetCoordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mycobot_communication::GetCoordsResponse> should match
// service_traits::DataType< ::mycobot_communication::GetCoords >
template<>
struct DataType< ::mycobot_communication::GetCoordsResponse>
{
  static const char* value()
  {
    return DataType< ::mycobot_communication::GetCoords >::value();
  }
  static const char* value(const ::mycobot_communication::GetCoordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYCOBOT_COMMUNICATION_MESSAGE_GETCOORDS_H
