// Generated by gencpp from file mecharm_communication/GetAngles.msg
// DO NOT EDIT!


#ifndef MECHARM_COMMUNICATION_MESSAGE_GETANGLES_H
#define MECHARM_COMMUNICATION_MESSAGE_GETANGLES_H

#include <ros/service_traits.h>


#include <mecharm_communication/GetAnglesRequest.h>
#include <mecharm_communication/GetAnglesResponse.h>


namespace mecharm_communication
{

struct GetAngles
{

typedef GetAnglesRequest Request;
typedef GetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAngles
} // namespace mecharm_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mecharm_communication::GetAngles > {
  static const char* value()
  {
    return "8ce9dd71b812ac669ff127f95e5ce8ab";
  }

  static const char* value(const ::mecharm_communication::GetAngles&) { return value(); }
};

template<>
struct DataType< ::mecharm_communication::GetAngles > {
  static const char* value()
  {
    return "mecharm_communication/GetAngles";
  }

  static const char* value(const ::mecharm_communication::GetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::mecharm_communication::GetAnglesRequest> should match
// service_traits::MD5Sum< ::mecharm_communication::GetAngles >
template<>
struct MD5Sum< ::mecharm_communication::GetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mecharm_communication::GetAngles >::value();
  }
  static const char* value(const ::mecharm_communication::GetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecharm_communication::GetAnglesRequest> should match
// service_traits::DataType< ::mecharm_communication::GetAngles >
template<>
struct DataType< ::mecharm_communication::GetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::mecharm_communication::GetAngles >::value();
  }
  static const char* value(const ::mecharm_communication::GetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mecharm_communication::GetAnglesResponse> should match
// service_traits::MD5Sum< ::mecharm_communication::GetAngles >
template<>
struct MD5Sum< ::mecharm_communication::GetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mecharm_communication::GetAngles >::value();
  }
  static const char* value(const ::mecharm_communication::GetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecharm_communication::GetAnglesResponse> should match
// service_traits::DataType< ::mecharm_communication::GetAngles >
template<>
struct DataType< ::mecharm_communication::GetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::mecharm_communication::GetAngles >::value();
  }
  static const char* value(const ::mecharm_communication::GetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MECHARM_COMMUNICATION_MESSAGE_GETANGLES_H
