// Generated by gencpp from file mecharm_communication/PumpStatus.msg
// DO NOT EDIT!


#ifndef MECHARM_COMMUNICATION_MESSAGE_PUMPSTATUS_H
#define MECHARM_COMMUNICATION_MESSAGE_PUMPSTATUS_H

#include <ros/service_traits.h>


#include <mecharm_communication/PumpStatusRequest.h>
#include <mecharm_communication/PumpStatusResponse.h>


namespace mecharm_communication
{

struct PumpStatus
{

typedef PumpStatusRequest Request;
typedef PumpStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PumpStatus
} // namespace mecharm_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mecharm_communication::PumpStatus > {
  static const char* value()
  {
    return "2a00a95bc76dbf1fced901f3346bdc4a";
  }

  static const char* value(const ::mecharm_communication::PumpStatus&) { return value(); }
};

template<>
struct DataType< ::mecharm_communication::PumpStatus > {
  static const char* value()
  {
    return "mecharm_communication/PumpStatus";
  }

  static const char* value(const ::mecharm_communication::PumpStatus&) { return value(); }
};


// service_traits::MD5Sum< ::mecharm_communication::PumpStatusRequest> should match
// service_traits::MD5Sum< ::mecharm_communication::PumpStatus >
template<>
struct MD5Sum< ::mecharm_communication::PumpStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mecharm_communication::PumpStatus >::value();
  }
  static const char* value(const ::mecharm_communication::PumpStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecharm_communication::PumpStatusRequest> should match
// service_traits::DataType< ::mecharm_communication::PumpStatus >
template<>
struct DataType< ::mecharm_communication::PumpStatusRequest>
{
  static const char* value()
  {
    return DataType< ::mecharm_communication::PumpStatus >::value();
  }
  static const char* value(const ::mecharm_communication::PumpStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mecharm_communication::PumpStatusResponse> should match
// service_traits::MD5Sum< ::mecharm_communication::PumpStatus >
template<>
struct MD5Sum< ::mecharm_communication::PumpStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mecharm_communication::PumpStatus >::value();
  }
  static const char* value(const ::mecharm_communication::PumpStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mecharm_communication::PumpStatusResponse> should match
// service_traits::DataType< ::mecharm_communication::PumpStatus >
template<>
struct DataType< ::mecharm_communication::PumpStatusResponse>
{
  static const char* value()
  {
    return DataType< ::mecharm_communication::PumpStatus >::value();
  }
  static const char* value(const ::mecharm_communication::PumpStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MECHARM_COMMUNICATION_MESSAGE_PUMPSTATUS_H
