(cl:defpackage mypalletizer_communication-msg
  (:use )
  (:export
   "<MYPALANGLES>"
   "MYPALANGLES"
   "<MYPALCOORDS>"
   "MYPALCOORDS"
   "<MYPALGRIPPERSTATUS>"
   "MYPALGRIPPERSTATUS"
   "<MYPALPUMPSTATUS>"
   "MYPALPUMPSTATUS"
   "<MYPALSETANGLES>"
   "MYPALSETANGLES"
   "<MYPALSETCOORDS>"
   "MYPALSETCOORDS"
  ))

