// Generated by gencpp from file mypalletizer_communication/GetCoords.msg
// DO NOT EDIT!


#ifndef MYPALLETIZER_COMMUNICATION_MESSAGE_GETCOORDS_H
#define MYPALLETIZER_COMMUNICATION_MESSAGE_GETCOORDS_H

#include <ros/service_traits.h>


#include <mypalletizer_communication/GetCoordsRequest.h>
#include <mypalletizer_communication/GetCoordsResponse.h>


namespace mypalletizer_communication
{

struct GetCoords
{

typedef GetCoordsRequest Request;
typedef GetCoordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCoords
} // namespace mypalletizer_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mypalletizer_communication::GetCoords > {
  static const char* value()
  {
    return "c42a43b20bb78e7c5bed54d699f9f272";
  }

  static const char* value(const ::mypalletizer_communication::GetCoords&) { return value(); }
};

template<>
struct DataType< ::mypalletizer_communication::GetCoords > {
  static const char* value()
  {
    return "mypalletizer_communication/GetCoords";
  }

  static const char* value(const ::mypalletizer_communication::GetCoords&) { return value(); }
};


// service_traits::MD5Sum< ::mypalletizer_communication::GetCoordsRequest> should match
// service_traits::MD5Sum< ::mypalletizer_communication::GetCoords >
template<>
struct MD5Sum< ::mypalletizer_communication::GetCoordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mypalletizer_communication::GetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::GetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypalletizer_communication::GetCoordsRequest> should match
// service_traits::DataType< ::mypalletizer_communication::GetCoords >
template<>
struct DataType< ::mypalletizer_communication::GetCoordsRequest>
{
  static const char* value()
  {
    return DataType< ::mypalletizer_communication::GetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::GetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mypalletizer_communication::GetCoordsResponse> should match
// service_traits::MD5Sum< ::mypalletizer_communication::GetCoords >
template<>
struct MD5Sum< ::mypalletizer_communication::GetCoordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mypalletizer_communication::GetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::GetCoordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypalletizer_communication::GetCoordsResponse> should match
// service_traits::DataType< ::mypalletizer_communication::GetCoords >
template<>
struct DataType< ::mypalletizer_communication::GetCoordsResponse>
{
  static const char* value()
  {
    return DataType< ::mypalletizer_communication::GetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::GetCoordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPALLETIZER_COMMUNICATION_MESSAGE_GETCOORDS_H
