// Generated by gencpp from file mypalletizer_communication/MypalCoords.msg
// DO NOT EDIT!


#ifndef MYPALLETIZER_COMMUNICATION_MESSAGE_MYPALCOORDS_H
#define MYPALLETIZER_COMMUNICATION_MESSAGE_MYPALCOORDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mypalletizer_communication
{
template <class ContainerAllocator>
struct MypalCoords_
{
  typedef MypalCoords_<ContainerAllocator> Type;

  MypalCoords_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)  {
    }
  MypalCoords_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , rx(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _rx_type;
  _rx_type rx;





  typedef boost::shared_ptr< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> const> ConstPtr;

}; // struct MypalCoords_

typedef ::mypalletizer_communication::MypalCoords_<std::allocator<void> > MypalCoords;

typedef boost::shared_ptr< ::mypalletizer_communication::MypalCoords > MypalCoordsPtr;
typedef boost::shared_ptr< ::mypalletizer_communication::MypalCoords const> MypalCoordsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mypalletizer_communication::MypalCoords_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mypalletizer_communication::MypalCoords_<ContainerAllocator1> & lhs, const ::mypalletizer_communication::MypalCoords_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.rx == rhs.rx;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mypalletizer_communication::MypalCoords_<ContainerAllocator1> & lhs, const ::mypalletizer_communication::MypalCoords_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mypalletizer_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c42a43b20bb78e7c5bed54d699f9f272";
  }

  static const char* value(const ::mypalletizer_communication::MypalCoords_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc42a43b20bb78e7cULL;
  static const uint64_t static_value2 = 0x5bed54d699f9f272ULL;
};

template<class ContainerAllocator>
struct DataType< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mypalletizer_communication/MypalCoords";
  }

  static const char* value(const ::mypalletizer_communication::MypalCoords_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 rx\n"
"# float32 ry\n"
"# float32 rz\n"
;
  }

  static const char* value(const ::mypalletizer_communication::MypalCoords_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.rx);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MypalCoords_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mypalletizer_communication::MypalCoords_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mypalletizer_communication::MypalCoords_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "rx: ";
    Printer<float>::stream(s, indent + "  ", v.rx);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYPALLETIZER_COMMUNICATION_MESSAGE_MYPALCOORDS_H
