// Generated by gencpp from file mypalletizer_communication/SetCoords.msg
// DO NOT EDIT!


#ifndef MYPALLETIZER_COMMUNICATION_MESSAGE_SETCOORDS_H
#define MYPALLETIZER_COMMUNICATION_MESSAGE_SETCOORDS_H

#include <ros/service_traits.h>


#include <mypalletizer_communication/SetCoordsRequest.h>
#include <mypalletizer_communication/SetCoordsResponse.h>


namespace mypalletizer_communication
{

struct SetCoords
{

typedef SetCoordsRequest Request;
typedef SetCoordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCoords
} // namespace mypalletizer_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mypalletizer_communication::SetCoords > {
  static const char* value()
  {
    return "09bb6605de65a0ada81d3779b54a5d09";
  }

  static const char* value(const ::mypalletizer_communication::SetCoords&) { return value(); }
};

template<>
struct DataType< ::mypalletizer_communication::SetCoords > {
  static const char* value()
  {
    return "mypalletizer_communication/SetCoords";
  }

  static const char* value(const ::mypalletizer_communication::SetCoords&) { return value(); }
};


// service_traits::MD5Sum< ::mypalletizer_communication::SetCoordsRequest> should match
// service_traits::MD5Sum< ::mypalletizer_communication::SetCoords >
template<>
struct MD5Sum< ::mypalletizer_communication::SetCoordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mypalletizer_communication::SetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::SetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypalletizer_communication::SetCoordsRequest> should match
// service_traits::DataType< ::mypalletizer_communication::SetCoords >
template<>
struct DataType< ::mypalletizer_communication::SetCoordsRequest>
{
  static const char* value()
  {
    return DataType< ::mypalletizer_communication::SetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::SetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mypalletizer_communication::SetCoordsResponse> should match
// service_traits::MD5Sum< ::mypalletizer_communication::SetCoords >
template<>
struct MD5Sum< ::mypalletizer_communication::SetCoordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mypalletizer_communication::SetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::SetCoordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mypalletizer_communication::SetCoordsResponse> should match
// service_traits::DataType< ::mypalletizer_communication::SetCoords >
template<>
struct DataType< ::mypalletizer_communication::SetCoordsResponse>
{
  static const char* value()
  {
    return DataType< ::mypalletizer_communication::SetCoords >::value();
  }
  static const char* value(const ::mypalletizer_communication::SetCoordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPALLETIZER_COMMUNICATION_MESSAGE_SETCOORDS_H
