// Generated by gencpp from file myarm_communication/GetAngles.msg
// DO NOT EDIT!


#ifndef MYARM_COMMUNICATION_MESSAGE_GETANGLES_H
#define MYARM_COMMUNICATION_MESSAGE_GETANGLES_H

#include <ros/service_traits.h>


#include <myarm_communication/GetAnglesRequest.h>
#include <myarm_communication/GetAnglesResponse.h>


namespace myarm_communication
{

struct GetAngles
{

typedef GetAnglesRequest Request;
typedef GetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAngles
} // namespace myarm_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myarm_communication::GetAngles > {
  static const char* value()
  {
    return "a5ee1c157b4205d64d317ae102e83e8c";
  }

  static const char* value(const ::myarm_communication::GetAngles&) { return value(); }
};

template<>
struct DataType< ::myarm_communication::GetAngles > {
  static const char* value()
  {
    return "myarm_communication/GetAngles";
  }

  static const char* value(const ::myarm_communication::GetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::myarm_communication::GetAnglesRequest> should match
// service_traits::MD5Sum< ::myarm_communication::GetAngles >
template<>
struct MD5Sum< ::myarm_communication::GetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myarm_communication::GetAngles >::value();
  }
  static const char* value(const ::myarm_communication::GetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myarm_communication::GetAnglesRequest> should match
// service_traits::DataType< ::myarm_communication::GetAngles >
template<>
struct DataType< ::myarm_communication::GetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::myarm_communication::GetAngles >::value();
  }
  static const char* value(const ::myarm_communication::GetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myarm_communication::GetAnglesResponse> should match
// service_traits::MD5Sum< ::myarm_communication::GetAngles >
template<>
struct MD5Sum< ::myarm_communication::GetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myarm_communication::GetAngles >::value();
  }
  static const char* value(const ::myarm_communication::GetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myarm_communication::GetAnglesResponse> should match
// service_traits::DataType< ::myarm_communication::GetAngles >
template<>
struct DataType< ::myarm_communication::GetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::myarm_communication::GetAngles >::value();
  }
  static const char* value(const ::myarm_communication::GetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYARM_COMMUNICATION_MESSAGE_GETANGLES_H
