// Generated by gencpp from file myarm_communication/GetAnglesRequest.msg
// DO NOT EDIT!


#ifndef MYARM_COMMUNICATION_MESSAGE_GETANGLESREQUEST_H
#define MYARM_COMMUNICATION_MESSAGE_GETANGLESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myarm_communication
{
template <class ContainerAllocator>
struct GetAnglesRequest_
{
  typedef GetAnglesRequest_<ContainerAllocator> Type;

  GetAnglesRequest_()
    {
    }
  GetAnglesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetAnglesRequest_

typedef ::myarm_communication::GetAnglesRequest_<std::allocator<void> > GetAnglesRequest;

typedef boost::shared_ptr< ::myarm_communication::GetAnglesRequest > GetAnglesRequestPtr;
typedef boost::shared_ptr< ::myarm_communication::GetAnglesRequest const> GetAnglesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myarm_communication::GetAnglesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace myarm_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::myarm_communication::GetAnglesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myarm_communication/GetAnglesRequest";
  }

  static const char* value(const ::myarm_communication::GetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::myarm_communication::GetAnglesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetAnglesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myarm_communication::GetAnglesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::myarm_communication::GetAnglesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MYARM_COMMUNICATION_MESSAGE_GETANGLESREQUEST_H
