// Generated by gencpp from file myarm_communication/MyArmGripperStatus.msg
// DO NOT EDIT!


#ifndef MYARM_COMMUNICATION_MESSAGE_MYARMGRIPPERSTATUS_H
#define MYARM_COMMUNICATION_MESSAGE_MYARMGRIPPERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myarm_communication
{
template <class ContainerAllocator>
struct MyArmGripperStatus_
{
  typedef MyArmGripperStatus_<ContainerAllocator> Type;

  MyArmGripperStatus_()
    : Status(false)  {
    }
  MyArmGripperStatus_(const ContainerAllocator& _alloc)
    : Status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Status_type;
  _Status_type Status;





  typedef boost::shared_ptr< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MyArmGripperStatus_

typedef ::myarm_communication::MyArmGripperStatus_<std::allocator<void> > MyArmGripperStatus;

typedef boost::shared_ptr< ::myarm_communication::MyArmGripperStatus > MyArmGripperStatusPtr;
typedef boost::shared_ptr< ::myarm_communication::MyArmGripperStatus const> MyArmGripperStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator1> & lhs, const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator2> & rhs)
{
  return lhs.Status == rhs.Status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator1> & lhs, const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myarm_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "513e93c68ef2f26ff494445b932bb052";
  }

  static const char* value(const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x513e93c68ef2f26fULL;
  static const uint64_t static_value2 = 0xf494445b932bb052ULL;
};

template<class ContainerAllocator>
struct DataType< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myarm_communication/MyArmGripperStatus";
  }

  static const char* value(const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Status\n"
;
  }

  static const char* value(const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyArmGripperStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myarm_communication::MyArmGripperStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myarm_communication::MyArmGripperStatus_<ContainerAllocator>& v)
  {
    s << indent << "Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYARM_COMMUNICATION_MESSAGE_MYARMGRIPPERSTATUS_H
