// Generated by gencpp from file myarm_communication/MyArmPumpStatus.msg
// DO NOT EDIT!


#ifndef MYARM_COMMUNICATION_MESSAGE_MYARMPUMPSTATUS_H
#define MYARM_COMMUNICATION_MESSAGE_MYARMPUMPSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myarm_communication
{
template <class ContainerAllocator>
struct MyArmPumpStatus_
{
  typedef MyArmPumpStatus_<ContainerAllocator> Type;

  MyArmPumpStatus_()
    : Status(false)
    , Pin1(0)
    , Pin2(0)  {
    }
  MyArmPumpStatus_(const ContainerAllocator& _alloc)
    : Status(false)
    , Pin1(0)
    , Pin2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Status_type;
  _Status_type Status;

   typedef int8_t _Pin1_type;
  _Pin1_type Pin1;

   typedef int8_t _Pin2_type;
  _Pin2_type Pin2;





  typedef boost::shared_ptr< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MyArmPumpStatus_

typedef ::myarm_communication::MyArmPumpStatus_<std::allocator<void> > MyArmPumpStatus;

typedef boost::shared_ptr< ::myarm_communication::MyArmPumpStatus > MyArmPumpStatusPtr;
typedef boost::shared_ptr< ::myarm_communication::MyArmPumpStatus const> MyArmPumpStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator1> & lhs, const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator2> & rhs)
{
  return lhs.Status == rhs.Status &&
    lhs.Pin1 == rhs.Pin1 &&
    lhs.Pin2 == rhs.Pin2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator1> & lhs, const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace myarm_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e36aa99b915b73d981939d713e2c8a1";
  }

  static const char* value(const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e36aa99b915b73dULL;
  static const uint64_t static_value2 = 0x981939d713e2c8a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myarm_communication/MyArmPumpStatus";
  }

  static const char* value(const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Status\n"
"int8 Pin1\n"
"int8 Pin2\n"
;
  }

  static const char* value(const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Status);
      stream.next(m.Pin1);
      stream.next(m.Pin2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyArmPumpStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myarm_communication::MyArmPumpStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myarm_communication::MyArmPumpStatus_<ContainerAllocator>& v)
  {
    s << indent << "Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Status);
    s << indent << "Pin1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Pin1);
    s << indent << "Pin2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Pin2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYARM_COMMUNICATION_MESSAGE_MYARMPUMPSTATUS_H
