// Generated by gencpp from file myarm_communication/SetAngles.msg
// DO NOT EDIT!


#ifndef MYARM_COMMUNICATION_MESSAGE_SETANGLES_H
#define MYARM_COMMUNICATION_MESSAGE_SETANGLES_H

#include <ros/service_traits.h>


#include <myarm_communication/SetAnglesRequest.h>
#include <myarm_communication/SetAnglesResponse.h>


namespace myarm_communication
{

struct SetAngles
{

typedef SetAnglesRequest Request;
typedef SetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngles
} // namespace myarm_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myarm_communication::SetAngles > {
  static const char* value()
  {
    return "6f95f19653eff9b1ac0a8f68b6693756";
  }

  static const char* value(const ::myarm_communication::SetAngles&) { return value(); }
};

template<>
struct DataType< ::myarm_communication::SetAngles > {
  static const char* value()
  {
    return "myarm_communication/SetAngles";
  }

  static const char* value(const ::myarm_communication::SetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::myarm_communication::SetAnglesRequest> should match
// service_traits::MD5Sum< ::myarm_communication::SetAngles >
template<>
struct MD5Sum< ::myarm_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myarm_communication::SetAngles >::value();
  }
  static const char* value(const ::myarm_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myarm_communication::SetAnglesRequest> should match
// service_traits::DataType< ::myarm_communication::SetAngles >
template<>
struct DataType< ::myarm_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::myarm_communication::SetAngles >::value();
  }
  static const char* value(const ::myarm_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myarm_communication::SetAnglesResponse> should match
// service_traits::MD5Sum< ::myarm_communication::SetAngles >
template<>
struct MD5Sum< ::myarm_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myarm_communication::SetAngles >::value();
  }
  static const char* value(const ::myarm_communication::SetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myarm_communication::SetAnglesResponse> should match
// service_traits::DataType< ::myarm_communication::SetAngles >
template<>
struct DataType< ::myarm_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::myarm_communication::SetAngles >::value();
  }
  static const char* value(const ::myarm_communication::SetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYARM_COMMUNICATION_MESSAGE_SETANGLES_H
