(cl:defpackage mybuddy_communication-msg
  (:use )
  (:export
   "<MYBUDDYANGLES>"
   "MYBUDDYANGLES"
   "<MYBUDDYCOORDS>"
   "MYBUDDYCOORDS"
   "<MYBUDDYGRIPPERSTATUS>"
   "MYBUDDYGRIPPERSTATUS"
   "<MYBUDDYPUMPSTATUS>"
   "MYBUDDYPUMPSTATUS"
   "<MYBUDDYSETANGLES>"
   "MYBUDDYSETANGLES"
   "<MYBUDDYSETCOORDS>"
   "MYBUDDYSETCOORDS"
  ))

