(cl:defpackage cobotx_a450_communication-msg
  (:use )
  (:export
   "<COBOTXANGLES>"
   "COBOTXANGLES"
   "<COBOTXCOORDS>"
   "COBOTXCOORDS"
   "<COBOTXGRIPPERSTATUS>"
   "COBOTXGRIPPERSTATUS"
   "<COBOTXPUMPSTATUS>"
   "COBOTXPUMPSTATUS"
   "<COBOTXSETANGLES>"
   "COBOTXSETANGLES"
   "<COBOTXSETCOORDS>"
   "COBOTXSETCOORDS"
  ))

