// Generated by gencpp from file mybuddy_communication/MybuddyPumpStatus.msg
// DO NOT EDIT!


#ifndef MYBUDDY_COMMUNICATION_MESSAGE_MYBUDDYPUMPSTATUS_H
#define MYBUDDY_COMMUNICATION_MESSAGE_MYBUDDYPUMPSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mybuddy_communication
{
template <class ContainerAllocator>
struct MybuddyPumpStatus_
{
  typedef MybuddyPumpStatus_<ContainerAllocator> Type;

  MybuddyPumpStatus_()
    : Status(false)
    , Pin1(0)
    , Pin2(0)  {
    }
  MybuddyPumpStatus_(const ContainerAllocator& _alloc)
    : Status(false)
    , Pin1(0)
    , Pin2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Status_type;
  _Status_type Status;

   typedef int8_t _Pin1_type;
  _Pin1_type Pin1;

   typedef int8_t _Pin2_type;
  _Pin2_type Pin2;





  typedef boost::shared_ptr< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MybuddyPumpStatus_

typedef ::mybuddy_communication::MybuddyPumpStatus_<std::allocator<void> > MybuddyPumpStatus;

typedef boost::shared_ptr< ::mybuddy_communication::MybuddyPumpStatus > MybuddyPumpStatusPtr;
typedef boost::shared_ptr< ::mybuddy_communication::MybuddyPumpStatus const> MybuddyPumpStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator1> & lhs, const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator2> & rhs)
{
  return lhs.Status == rhs.Status &&
    lhs.Pin1 == rhs.Pin1 &&
    lhs.Pin2 == rhs.Pin2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator1> & lhs, const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mybuddy_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e36aa99b915b73d981939d713e2c8a1";
  }

  static const char* value(const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e36aa99b915b73dULL;
  static const uint64_t static_value2 = 0x981939d713e2c8a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybuddy_communication/MybuddyPumpStatus";
  }

  static const char* value(const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Status\n"
"int8 Pin1\n"
"int8 Pin2\n"
;
  }

  static const char* value(const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Status);
      stream.next(m.Pin1);
      stream.next(m.Pin2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MybuddyPumpStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybuddy_communication::MybuddyPumpStatus_<ContainerAllocator>& v)
  {
    s << indent << "Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Status);
    s << indent << "Pin1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Pin1);
    s << indent << "Pin2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.Pin2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBUDDY_COMMUNICATION_MESSAGE_MYBUDDYPUMPSTATUS_H
