// Generated by gencpp from file mybuddy_communication/MybuddyGripperStatus.msg
// DO NOT EDIT!


#ifndef MYBUDDY_COMMUNICATION_MESSAGE_MYBUDDYGRIPPERSTATUS_H
#define MYBUDDY_COMMUNICATION_MESSAGE_MYBUDDYGRIPPERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mybuddy_communication
{
template <class ContainerAllocator>
struct MybuddyGripperStatus_
{
  typedef MybuddyGripperStatus_<ContainerAllocator> Type;

  MybuddyGripperStatus_()
    : Status(false)  {
    }
  MybuddyGripperStatus_(const ContainerAllocator& _alloc)
    : Status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Status_type;
  _Status_type Status;





  typedef boost::shared_ptr< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MybuddyGripperStatus_

typedef ::mybuddy_communication::MybuddyGripperStatus_<std::allocator<void> > MybuddyGripperStatus;

typedef boost::shared_ptr< ::mybuddy_communication::MybuddyGripperStatus > MybuddyGripperStatusPtr;
typedef boost::shared_ptr< ::mybuddy_communication::MybuddyGripperStatus const> MybuddyGripperStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator1> & lhs, const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator2> & rhs)
{
  return lhs.Status == rhs.Status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator1> & lhs, const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mybuddy_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "513e93c68ef2f26ff494445b932bb052";
  }

  static const char* value(const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x513e93c68ef2f26fULL;
  static const uint64_t static_value2 = 0xf494445b932bb052ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybuddy_communication/MybuddyGripperStatus";
  }

  static const char* value(const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Status\n"
;
  }

  static const char* value(const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MybuddyGripperStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybuddy_communication::MybuddyGripperStatus_<ContainerAllocator>& v)
  {
    s << indent << "Status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBUDDY_COMMUNICATION_MESSAGE_MYBUDDYGRIPPERSTATUS_H
