// Generated by gencpp from file mybuddy_communication/SetAngles.msg
// DO NOT EDIT!


#ifndef MYBUDDY_COMMUNICATION_MESSAGE_SETANGLES_H
#define MYBUDDY_COMMUNICATION_MESSAGE_SETANGLES_H

#include <ros/service_traits.h>


#include <mybuddy_communication/SetAnglesRequest.h>
#include <mybuddy_communication/SetAnglesResponse.h>


namespace mybuddy_communication
{

struct SetAngles
{

typedef SetAnglesRequest Request;
typedef SetAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAngles
} // namespace mybuddy_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mybuddy_communication::SetAngles > {
  static const char* value()
  {
    return "9d0765c7fea1de2870e482fc85d83cb1";
  }

  static const char* value(const ::mybuddy_communication::SetAngles&) { return value(); }
};

template<>
struct DataType< ::mybuddy_communication::SetAngles > {
  static const char* value()
  {
    return "mybuddy_communication/SetAngles";
  }

  static const char* value(const ::mybuddy_communication::SetAngles&) { return value(); }
};


// service_traits::MD5Sum< ::mybuddy_communication::SetAnglesRequest> should match
// service_traits::MD5Sum< ::mybuddy_communication::SetAngles >
template<>
struct MD5Sum< ::mybuddy_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mybuddy_communication::SetAngles >::value();
  }
  static const char* value(const ::mybuddy_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mybuddy_communication::SetAnglesRequest> should match
// service_traits::DataType< ::mybuddy_communication::SetAngles >
template<>
struct DataType< ::mybuddy_communication::SetAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::mybuddy_communication::SetAngles >::value();
  }
  static const char* value(const ::mybuddy_communication::SetAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mybuddy_communication::SetAnglesResponse> should match
// service_traits::MD5Sum< ::mybuddy_communication::SetAngles >
template<>
struct MD5Sum< ::mybuddy_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mybuddy_communication::SetAngles >::value();
  }
  static const char* value(const ::mybuddy_communication::SetAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mybuddy_communication::SetAnglesResponse> should match
// service_traits::DataType< ::mybuddy_communication::SetAngles >
template<>
struct DataType< ::mybuddy_communication::SetAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::mybuddy_communication::SetAngles >::value();
  }
  static const char* value(const ::mybuddy_communication::SetAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYBUDDY_COMMUNICATION_MESSAGE_SETANGLES_H
