(cl:defpackage ultraarm_communication-msg
  (:use )
  (:export
   "<ULTRAARMANGLES>"
   "ULTRAARMANGLES"
   "<ULTRAARMCOORDS>"
   "ULTRAARMCOORDS"
   "<ULTRAARMGRIPPERSTATUS>"
   "ULTRAARMGRIPPERSTATUS"
   "<ULTRAARMPUMPSTATUS>"
   "ULTRAARMPUMPSTATUS"
   "<ULTRAARMSETANGLES>"
   "ULTRAARMSETANGLES"
   "<ULTRAARMSETCOORDS>"
   "ULTRAARMSETCOORDS"
  ))

