// Generated by gencpp from file ultraarm_communication/GetCoords.msg
// DO NOT EDIT!


#ifndef ULTRAARM_COMMUNICATION_MESSAGE_GETCOORDS_H
#define ULTRAARM_COMMUNICATION_MESSAGE_GETCOORDS_H

#include <ros/service_traits.h>


#include <ultraarm_communication/GetCoordsRequest.h>
#include <ultraarm_communication/GetCoordsResponse.h>


namespace ultraarm_communication
{

struct GetCoords
{

typedef GetCoordsRequest Request;
typedef GetCoordsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCoords
} // namespace ultraarm_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ultraarm_communication::GetCoords > {
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::ultraarm_communication::GetCoords&) { return value(); }
};

template<>
struct DataType< ::ultraarm_communication::GetCoords > {
  static const char* value()
  {
    return "ultraarm_communication/GetCoords";
  }

  static const char* value(const ::ultraarm_communication::GetCoords&) { return value(); }
};


// service_traits::MD5Sum< ::ultraarm_communication::GetCoordsRequest> should match
// service_traits::MD5Sum< ::ultraarm_communication::GetCoords >
template<>
struct MD5Sum< ::ultraarm_communication::GetCoordsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ultraarm_communication::GetCoords >::value();
  }
  static const char* value(const ::ultraarm_communication::GetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ultraarm_communication::GetCoordsRequest> should match
// service_traits::DataType< ::ultraarm_communication::GetCoords >
template<>
struct DataType< ::ultraarm_communication::GetCoordsRequest>
{
  static const char* value()
  {
    return DataType< ::ultraarm_communication::GetCoords >::value();
  }
  static const char* value(const ::ultraarm_communication::GetCoordsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ultraarm_communication::GetCoordsResponse> should match
// service_traits::MD5Sum< ::ultraarm_communication::GetCoords >
template<>
struct MD5Sum< ::ultraarm_communication::GetCoordsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ultraarm_communication::GetCoords >::value();
  }
  static const char* value(const ::ultraarm_communication::GetCoordsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ultraarm_communication::GetCoordsResponse> should match
// service_traits::DataType< ::ultraarm_communication::GetCoords >
template<>
struct DataType< ::ultraarm_communication::GetCoordsResponse>
{
  static const char* value()
  {
    return DataType< ::ultraarm_communication::GetCoords >::value();
  }
  static const char* value(const ::ultraarm_communication::GetCoordsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ULTRAARM_COMMUNICATION_MESSAGE_GETCOORDS_H
