// Generated by gencpp from file ultraarm_communication/PumpStatus.msg
// DO NOT EDIT!


#ifndef ULTRAARM_COMMUNICATION_MESSAGE_PUMPSTATUS_H
#define ULTRAARM_COMMUNICATION_MESSAGE_PUMPSTATUS_H

#include <ros/service_traits.h>


#include <ultraarm_communication/PumpStatusRequest.h>
#include <ultraarm_communication/PumpStatusResponse.h>


namespace ultraarm_communication
{

struct PumpStatus
{

typedef PumpStatusRequest Request;
typedef PumpStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PumpStatus
} // namespace ultraarm_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ultraarm_communication::PumpStatus > {
  static const char* value()
  {
    return "c57caedf4aafd0b59704d2f3b16e0f35";
  }

  static const char* value(const ::ultraarm_communication::PumpStatus&) { return value(); }
};

template<>
struct DataType< ::ultraarm_communication::PumpStatus > {
  static const char* value()
  {
    return "ultraarm_communication/PumpStatus";
  }

  static const char* value(const ::ultraarm_communication::PumpStatus&) { return value(); }
};


// service_traits::MD5Sum< ::ultraarm_communication::PumpStatusRequest> should match
// service_traits::MD5Sum< ::ultraarm_communication::PumpStatus >
template<>
struct MD5Sum< ::ultraarm_communication::PumpStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ultraarm_communication::PumpStatus >::value();
  }
  static const char* value(const ::ultraarm_communication::PumpStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ultraarm_communication::PumpStatusRequest> should match
// service_traits::DataType< ::ultraarm_communication::PumpStatus >
template<>
struct DataType< ::ultraarm_communication::PumpStatusRequest>
{
  static const char* value()
  {
    return DataType< ::ultraarm_communication::PumpStatus >::value();
  }
  static const char* value(const ::ultraarm_communication::PumpStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ultraarm_communication::PumpStatusResponse> should match
// service_traits::MD5Sum< ::ultraarm_communication::PumpStatus >
template<>
struct MD5Sum< ::ultraarm_communication::PumpStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ultraarm_communication::PumpStatus >::value();
  }
  static const char* value(const ::ultraarm_communication::PumpStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ultraarm_communication::PumpStatusResponse> should match
// service_traits::DataType< ::ultraarm_communication::PumpStatus >
template<>
struct DataType< ::ultraarm_communication::PumpStatusResponse>
{
  static const char* value()
  {
    return DataType< ::ultraarm_communication::PumpStatus >::value();
  }
  static const char* value(const ::ultraarm_communication::PumpStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ULTRAARM_COMMUNICATION_MESSAGE_PUMPSTATUS_H
